# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.12
        environment:
          - GO111MODULE: "on"
      - image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
        name: es
        environment:
          cluster.name: test
          discovery.type: single-node
          ELASTIC_PASSWORD: changeme
          xpack.security.enabled: "true"
      - image: docker.elastic.co/kibana/kibana:7.4.0
        name: kb
        environment:
          ELASTICSEARCH_HOSTS: http://es:9200
          ELASTICSEARCH_USERNAME: elastic
          ELASTICSEARCH_PASSWORD: changeme
    working_directory: /go/src/github.com/disaster37/go-kibana-rest
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-pkg-cache
      - run: until $(curl --output /dev/null --silent --head --fail -u elastic:changeme http://kb:5601); do sleep 5; done
      - run: go test ./... -v
      - save_cache:
          key: v1-pkg-cache
          paths:
            - "/go/pkg"
  build:
    docker:
      - image: circleci/golang:1.12
        environment:
          - GO111MODULE: "on"
    working_directory: /go/src/github.com/disaster37/go-kibana-rest
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-pkg-cache
      - run: go build
workflows:
  version: 2
  build-workflow:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - build:
          requires:
            - test
          filters:
            tags:
              only: /.*/